Add contents to the docs
pasqal-io/qadence2-ir pull request #21
Opened 2024-11-29 09:07 UTC by pimvenderbosch

In this PR the contents of the documentation pages will be filled.

- [ ] Improve docstrings
- [ ] Write general documentation pages

2024-12-02 14:41 UTC, pimvenderbosch commented
Hi @RolandMacDoland and @Doomsk,

I've completed half of this PR, namely the updating of docstrings. Possibly a good idea to already review this part, so that the eventual review is not massive.

Best,
Pim

2024-12-03 09:09 UTC, pimvenderbosch commented on qadence2_ir/irast.py
>  class AST:
The `IRBuilder.parse_sequence` implementation in Qadence 2 expressions translates an expression tree into an `AST` object, see [here](https://github.com/pasqal-io/qadence2-expressions/blob/3fb112cf684c8dab28fb4535e8cb1355189d4be6/qadence2_expressions/ircompiler.py#L60). Other front-ends need to provide their own implementation.

2024-12-05 14:02 UTC, Doomsk requested changes
Thanks for the great work. There are a few comments to improve the documentation

2024-12-05 15:10 UTC, Doomsk requested changes
Great work! A few comments and I think that's it

2024-12-05 15:10 UTC, Doomsk commented on docs/examples.md
> +## Examples
This one is not being used or referenced in the documentation. Is it expected, i.e. to be used later somewhere in the documentation?

2024-12-06 07:45 UTC, pimvenderbosch commented on docs/examples.md
> +## Examples
Indeed, I'm still working on the examples page right now.

2024-12-09 12:56 UTC, Doomsk approved these changes

2024-12-09 12:59 UTC, pimvenderbosch commented
Created #22 with ideas of improving the documentation at a later stage.

2024-12-09 13:00 UTC, merged